### ISSUE TITLE
Application page TODO

### ISSUE THREAD

**Issue by henrytwo** [hack-the-6ix/hackthe6ix-hacker-portal#16]
Urgent
- [x] Verify that frontend validators match the backend (https://github.com/hack-the-6ix/hackthe6ix-backend/blob/6341a72e258d9d4574f8e6211160b197fbfdc692/src/models/user/fields.ts)
- [x] Validation does not exist
- [x] File upload does not care about file type
- [x] File upload allows interaction during disabled state
- [x] Textarea is same color during disabled state
- [x] Big arrow ipad issue?
- [x] Fields appear to get cut off on small screen (iphone 6)
![image](https://user-images.githubusercontent.com/17518332/125021938-990e0780-e049-11eb-8c33-62d5baf76a58.png)
- [x] Dropdowns are not the same color as input fields when disabled 
- [x] Postal code update
- [x] Safari checkbox
- [x] Phone number expand digits
- [x] Do not validate form on save
- [x] do not accept resume if disabled
- [x] Combo box for school + POS
- [x] Resume is not highlighted when it fails validation
- [x] Force postal code to be uppercase
- [x] URL validation is wonky
- [x] Resolve error when field is updated?
![image](https://user-images.githubusercontent.com/17518332/125142347-80ebc600-e0e5-11eb-91b5-a1d79361fb44.png)

Less urgent
- [x] Message banner thing
~- [ ] Message bubble hover thing~
